//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace zSession.Base.DBModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class mainEntities : DbContext
    {
        public mainEntities()
            : base("name=mainEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Session_Chat> Session_Chat { get; set; }
        public DbSet<Session_Dpt_Roles> Session_Dpt_Roles { get; set; }
        public DbSet<Session_Dpt_Users> Session_Dpt_Users { get; set; }
        public DbSet<Session_Dpts> Session_Dpts { get; set; }
        public DbSet<Session_DptTypes> Session_DptTypes { get; set; }
        public DbSet<Session_Grant_Dpts> Session_Grant_Dpts { get; set; }
        public DbSet<Session_Grant_Roles> Session_Grant_Roles { get; set; }
        public DbSet<Session_Grant_Users> Session_Grant_Users { get; set; }
        public DbSet<Session_LastOperation> Session_LastOperation { get; set; }
        public DbSet<Session_Powers> Session_Powers { get; set; }
        public DbSet<Session_Roles> Session_Roles { get; set; }
        public DbSet<Session_Users> Session_Users { get; set; }
    }
}
